# Generated by Django 5.0.6 on 2024-06-17 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('disciplina_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('lininvest_id', models.BigIntegerField(db_column='linInvest_id', primary_key=True, serialize=False)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Linea_Investigacion',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solicitud_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('detalle', models.TextField()),
                ('oficio', models.TextField()),
                ('etapa', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('registro_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('servicios', models.JSONField(blank=True, null=True)),
                ('mision', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('historia', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('instituto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('mision', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('historia', models.TextField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('comite_directivo', models.TextField(blank=True, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('nombre_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_instituto', models.CharField(blank=True, max_length=255, null=True)),
                ('url_instituto', models.TextField(blank=True, null=True)),
                ('url_facebook', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Instituto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('investigador_principal', models.CharField(max_length=255)),
                ('coinvestigadores', models.JSONField()),
                ('nombre_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_referencial', models.CharField(blank=True, max_length=255, null=True)),
                ('etapa', models.CharField(blank=True, max_length=255, null=True)),
                ('duracion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('doi', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('iba', models.CharField(max_length=25)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usuario_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_paterno', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=45, null=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('fecha_eleccion', models.DateField(blank=True, null=True)),
                ('fecha_culminacion', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('regimen', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('unidad_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=250)),
                ('facultad', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Unidad',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('documento_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('archivo_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.laboratorio')),
            ],
            options={
                'db_table': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equipo_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_equipo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('marca_modelo', models.CharField(max_length=255)),
                ('fecha_adquisicion', models.DateTimeField()),
                ('proveedor', models.CharField(max_length=100)),
                ('contacto_proveedor', models.CharField(max_length=100)),
                ('codigo_patrimonio', models.CharField(max_length=50)),
                ('accesorio', models.CharField(max_length=255)),
                ('insumos', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.laboratorio')),
            ],
            options={
                'db_table': 'Equipo',
            },
        ),
        migrations.CreateModel(
            name='EventoGaleria',
            fields=[
                ('galeria_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.laboratorio')),
            ],
            options={
                'db_table': 'Evento_galeria',
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('funcion_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('funcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.instituto')),
            ],
            options={
                'db_table': 'Funcion',
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('convenio_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivo', models.TextField()),
                ('detalles', models.TextField()),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.instituto')),
            ],
            options={
                'db_table': 'Convenio',
            },
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('poi_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('nombre_poi', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_poi', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.instituto')),
            ],
            options={
                'db_table': 'Poi',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('publicacion_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.proyecto')),
            ],
            options={
                'db_table': 'Publicacion',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('materiales', models.FloatField()),
                ('mano_obra', models.FloatField()),
                ('ci_mano_obra', models.FloatField()),
                ('ci_deprec_equi', models.FloatField()),
                ('ci_deprec_edif', models.FloatField()),
                ('ci_util_limp', models.FloatField()),
                ('ci_util_aseo', models.FloatField()),
                ('ci_mantto', models.FloatField()),
                ('ci_servicios', models.FloatField()),
                ('estado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.instituto')),
            ],
            options={
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Entity3',
            fields=[
                ('lininvest', models.OneToOneField(db_column='linInvest_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.lineainvestigacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.proyecto')),
            ],
            options={
                'db_table': 'Entity3',
                'unique_together': {('lininvest', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='Entity5',
            fields=[
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.solicitud')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.equipo')),
            ],
            options={
                'db_table': 'Entity5',
                'unique_together': {('solicitud', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='Entity6',
            fields=[
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.laboratorio')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.disciplinas')),
            ],
            options={
                'db_table': 'Entity6',
                'unique_together': {('registro', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='RolInst',
            fields=[
                ('instituto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.instituto')),
                ('tipo_rol', models.SmallIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.users')),
            ],
            options={
                'db_table': 'Rol_Inst',
                'unique_together': {('instituto', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudInst',
            fields=[
                ('instituto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.instituto')),
                ('state', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('field_updated_at', models.DateTimeField(db_column='\x7fupdated_at')),
                ('solicitud_estado', models.SmallIntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.proyecto')),
            ],
            options={
                'db_table': 'Solicitud_Inst',
                'unique_together': {('instituto', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudLab',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.proyecto')),
                ('state', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('solicitud_estado', models.SmallIntegerField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.laboratorio')),
            ],
            options={
                'db_table': 'Solicitud_Lab',
                'unique_together': {('proyecto', 'registro')},
            },
        ),
        migrations.CreateModel(
            name='SolitudUnidad',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.proyecto')),
                ('state', models.SmallIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('created_at_field', models.DateTimeField(db_column="created_at'")),
                ('solicitud_estado', models.SmallIntegerField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.unidad')),
            ],
            options={
                'db_table': 'Solitud_Unidad',
                'unique_together': {('proyecto', 'unidad')},
            },
        ),
        migrations.CreateModel(
            name='RolLab',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.users')),
                ('tipo_rol', models.SmallIntegerField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.laboratorio')),
            ],
            options={
                'db_table': 'Rol_Lab',
                'unique_together': {('usuario', 'registro')},
            },
        ),
        migrations.CreateModel(
            name='RolUni',
            fields=[
                ('unidad', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sileii.unidad')),
                ('tipo_rol', models.SmallIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sileii.users')),
            ],
            options={
                'db_table': 'Rol_Uni',
                'unique_together': {('unidad', 'usuario')},
            },
        ),
    ]
